[package]
name = "img2webp"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
image = "0.24"
webp = "0.2"
rayon = "1.5"
wasm-bindgen = "0.2"

[profile.release]
opt-level = 3
lto = true